FROM docker.io/ollama/ollama:0.3.12

# https://stackoverflow.com/questions/78688712/how-to-build-in-mistral-model-into-ollama-permanently
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
        curl
RUN ollama serve & \
    curl --retry 10 --retry-connrefused --retry-delay 1 http://localhost:11434/ && \
    curl -X POST -d '{"name": "llama3.2"}' http://localhost:11434/api/pull
